name: flutter_palu
description: "Aplikasi Solusi Rumah Tangga."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.6.1
  location: ^6.0.1
  image: ^4.1.7
  go_router: ^14.2.0


dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  # freezed: ^2.5.2

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banks/
    - assets/images/categories/
    - assets/images/products/
    - assets/icons/